run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - stylecheck
    - revive
    - unconvert
    - goconst
    - gocyclo
    - gocognit
    - asciicheck
    - copyloopvar
    - gocritic
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - unparam
    - dogsled

linters-settings:
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment # Optimization only, can break GORM struct tags
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (io.Closer).Close
      - (*github.com/emersion/go-imap/v2/imapclient.FetchMessageData).Close
      - (*github.com/emersion/go-imap/v2/imapclient.Client).Close
      - (*github.com/gen2brain/go-fitz.Document).Close
      - (*gin-gonic/gin.Engine).Run
      - (*gorm.io/gorm.DB).AutoMigrate
      - encoding/json.Unmarshal
      - os.RemoveAll
      - os.Remove
      - fmt.Sscanf
  gocyclo:
    min-complexity: 25
  gocognit:
    min-complexity: 40
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: kincart
  revive:
    rules:
      - name: blank-imports
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
  stylecheck:
    checks:
      - all
      - -ST1000 # Package comments - not required for internal packages

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
