run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - stylecheck
    - revive
    - unconvert
    - goconst
    - gocyclo
    - gocognit
    - asciicheck
    - copyloopvar
    - gocritic
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - unparam
    - dogsled

linters-settings:
  govet:
    enable:
      - shadow
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: kincart
  revive:
    rules:
      - name: blank-imports
      - name: context-as-first-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
