import { precacheAndRoute } from 'workbox-precaching';
import localforage from 'localforage';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Configure localforage for shared files
localforage.config({
    name: 'KinCart',
    storeName: 'shared_files'
});

/**
 * Intercept the Web Share Target POST request.
 * Android will POST to /share-target with the shared files.
 */
self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);

    // Check if this is the share target endpoint
    if (event.request.method === 'POST' && url.pathname === '/share-target') {
        event.respondWith(
            (async () => {
                try {
                    const formData = await event.request.formData();
                    const files = formData.getAll('receipts');

                    if (files && files.length > 0) {
                        // We store the files as Blobs in IndexedDB via localforage
                        // We only support one "pending" share session at a time for simplicity
                        const filesToStore = files.map(file => ({
                            name: file.name,
                            blob: file, // File objects are valid Blobs
                            type: file.type,
                            timestamp: Date.now()
                        }));

                        await localforage.setItem('pending_shared_receipts', filesToStore);
                    }

                    // Use a 303 See Other redirect to send the user to our React route
                    return Response.redirect('/import-receipt?shared=true', 303);
                } catch (error) {
                    console.error('Service Worker: Error handling share target:', error);
                    // Fallback redirect to dashboard with error flag
                    return Response.redirect('/?shared_error=internal_sw_error', 303);
                }
            })()
        );
    }
});

// Optional: Listen for skipWaiting messages from the frontend to allow manual updates
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
